import {mountCertificate} from './interaction.mjs';
import {BookingJourney,createPreviewKey} from './booking-state.mjs';
const offer=JSON.parse(document.querySelector('#offer-data').textContent);
const slots=JSON.parse(document.querySelector('#slot-data').textContent);
const surface=document.querySelector('.certificate');mountCertificate(surface);
const key=createPreviewKey();const journey=new BookingJourney(offer,key);
const contact={firstName:'',email:'',phone:'',acknowledge:false,marketing:false};
let step=0,displayZone=offer.timezone;const content=document.querySelector('.journey-content'),progress=document.querySelector('.progress span'),stepLabel=document.querySelector('[data-progress-label]');
const questions=['Are you married or cohabiting, with a combined household income of at least $75,000?','Do you have a major credit card for travel incidentals and travel at least twice a year?'];
const created=new Map();let requests=[],attempts=0;
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric',timeZone:displayZone}).format(new Date(s));
const time=s=>new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit',timeZoneName:'short',timeZone:displayZone}).format(new Date(s));
const totalStep=5;
function foot(next='Continue'){return `<div class="step-footer"><button class="button quiet" data-back>Back</button><button class="button" data-next>${next}</button></div>`;}
function showError(message){const el=content.querySelector('.inline-error');el.textContent=message;el.hidden=false;el.focus();}
function render(focus=true){
 progress.style.width=((step+1)/totalStep*100)+'%';stepLabel.textContent=step<2?`Question ${step+1} of 2`:step===2?'Your details':step===3?'Your presentation time':'Your confirmation';
 if(step<2){const answer=journey.answers['q'+(step+1)];content.innerHTML=`<section class="step"><h2 tabindex="-1">${questions[step]}</h2><p class="explain">${step===0?'Both qualified adults attend the 45–60 minute presentation together. Accommodation capacity is shown separately on your certificate.':'These are the existing certificate qualification questions. Your answers stay with you when you go back.'}</p><div class="choices"><button class="choice" data-answer="yes" aria-pressed="${answer==='yes'}">Yes</button><button class="choice" data-answer="no" aria-pressed="${answer==='no'}">No</button></div><p class="inline-error" tabindex="-1" role="alert" hidden></p>${foot()}</section>`;}
 else if(step===2){content.innerHTML=`<section class="step"><h2 tabindex="-1">Where should your confirmation go?</h2><p class="explain">Enter your details once. Your presentation time comes next; travel dates are arranged later with the reservation agency.</p><form id="contact-form"><div class="form-grid"><div class="field"><label for="firstName">First name</label><input id="firstName" name="firstName" autocomplete="given-name" required value="${escape(contact.firstName)}"></div><div class="field"><label for="email">Email</label><input id="email" name="email" type="email" autocomplete="email" required value="${escape(contact.email)}"></div><div class="field wide"><label for="phone">Phone <span class="muted">(optional)</span></label><input id="phone" name="phone" type="tel" autocomplete="tel" value="${escape(contact.phone)}"></div></div><label class="consent-row"><input name="acknowledge" type="checkbox" required ${contact.acknowledge?'checked':''}><span>${escape(offer.calendarConsent)}</span></label><label class="consent-row"><input name="marketing" type="checkbox" ${contact.marketing?'checked':''}><span>${offer.marketingConsent}</span></label><p class="inline-error" tabindex="-1" role="alert" hidden></p><div class="step-footer"><button type="button" class="button quiet" data-back>Back</button><button type="submit" class="button">Choose my presentation time</button></div></form><p class="review-disclosure">Design review: use <button class="button quiet" data-demo-details>demo details</button>. This preview sends no contact information.</p></section>`;}
 else if(step===3){const selected=journey.slot;content.innerHTML=`<section class="step"><h2 tabindex="-1">One time. Both of you.</h2><p class="explain">Choose your 45–60 minute live presentation. This is an appointment, not a travel reservation.</p><p class="review-disclosure">Preview dates from the existing schedule, captured September 11. Availability and booking are simulated here.</p><div class="timezone-row"><span class="muted">Show appointment times in</span><select aria-label="Appointment timezone"><option value="America/Los_Angeles">Pacific time</option><option value="America/Denver">Mountain time</option><option value="America/Chicago">Central time</option><option value="America/New_York">Eastern time</option></select></div>${slots.days.map(d=>`<section class="slot-day"><h3>${date(d.slots[0].startTime)}</h3><div class="slot-buttons">${d.slots.filter(s=>s.available).map(s=>`<button class="slot-button" data-slot="${s.startTime}" aria-pressed="${selected===s.startTime}">${time(s.startTime)}</button>`).join('')}</div></section>`).join('')}${selected?`<div class="selected-summary"><b>${date(selected)} · ${time(selected)}</b><p>${escape(offer.title)} · ${escape(offer.certificateId)}</p><p>Your selection stays here if you go back or retry.</p></div>`:''}<p class="inline-error" tabindex="-1" role="alert" hidden></p>${foot('Confirm preview appointment')}</section>`;content.querySelector('select').value=displayZone;}
 else{const result=journey.confirmation;content.innerHTML=`<section class="step"><div class="confirmation-mark" aria-hidden="true">✓</div><h2 tabindex="-1">Your preview appointment is confirmed.</h2><p class="review-disclosure">Demonstration only. No live seat has been reserved and no messages have been sent.</p><dl class="confirmation-details"><dt>Presentation</dt><dd>${date(result.startTime)}<br>${time(result.startTime)}</dd><dt>Certificate</dt><dd>${escape(offer.title)}<br>${escape(offer.certificateId)}</dd><dt>Travelers</dt><dd>Both qualified adults attend. ${offer.family==='condo'?'The condo accommodates up to four travelers.':'Accommodation capacity follows your certificate terms.'}</dd><dt>Appointment</dt><dd>${escape(result.eventId)}</dd></dl><a class="button" href="#certificate">View your certificate</a><div class="followthrough"><div><span>1</span><section><b>Confirmation and access</b><p>The live calendar is configured to confirm bookings and send an invitation. Delivery still needs a controlled live test.</p></section></div><div><span>2</span><section><b>Reminders and check-in</b><p>Existing reminder and check-in instructions are preserved. Their timing has not been changed in this preview.</p></section></div><div><span>3</span><section><b>After your presentation</b><p>Certificate delivery and attendance follow-up must use the existing HVM workflow, once verified.</p></section></div></div><details class="terms-details"><summary>Review the test booking evidence</summary><div><pre class="proof-note">${escape(JSON.stringify({mode:'preview',...journey.payload(contact),email:'[test address]',firstName:'[test name]',phone:'[test phone]',response:result,createRequests:attempts,appointmentsCreated:created.size},null,2))}</pre></div></details></section>`;}
 if(focus)content.querySelector('h2')?.focus({preventScroll:true});
}
function noMatch(){content.innerHTML=`<section class="step no-match"><h2 tabindex="-1">This certificate isn’t the right match today.</h2><p class="explain">Thank you for checking. You can review your answers or explore the other existing offers.</p><div class="step-footer"><button class="button secondary" data-revise>Review my answers</button><a href="/index.html?offers=1">See other offers</a></div></section>`;content.querySelector('h2').focus({preventScroll:true});}
content.addEventListener('click',async e=>{
 const target=e.target.closest('button');if(!target)return;
 if(target.hasAttribute('data-demo-details')){contact.firstName='Preview';contact.email='preview@example.invalid';contact.phone='';render(false);return;}
 if(target.hasAttribute('data-revise')){step=0;render();return;}
 if(target.hasAttribute('data-answer')){journey.answer('q'+(step+1),target.dataset.answer);content.querySelectorAll('[data-answer]').forEach(b=>b.setAttribute('aria-pressed',String(b===target)));return;}
 if(target.hasAttribute('data-back')){step=Math.max(0,step-1);journey.back();render();return;}
 if(target.hasAttribute('data-slot')){journey.select(target.dataset.slot);render(false);content.querySelector(`[data-slot="${journey.slot}"]`)?.focus({preventScroll:true});return;}
 if(!target.hasAttribute('data-next'))return;
 if(step<2){const answer=journey.answers['q'+(step+1)];if(!answer){showError('Choose Yes or No to continue.');return;}if(answer==='no'){noMatch();return;}step++;render();return;}
 if(step===3){if(!journey.slot){showError('Choose one presentation time.');return;}target.disabled=true;target.textContent='Confirming your selection…';content.querySelector('[data-back]').disabled=true;
  try{await journey.confirm(async payload=>{attempts++;requests.push(payload);await new Promise(r=>setTimeout(r,500));if(!created.has(payload.idempotencyKey))created.set(payload.idempotencyKey,{ok:true,eventId:'preview-'+key.slice(-8),startTime:payload.startTime,timezone:payload.timezone});return created.get(payload.idempotencyKey)},contact);step=4;render();}catch(error){render(false);showError(error.message);}
 }
});
content.addEventListener('input',e=>{if(e.target.name in contact)contact[e.target.name]=e.target.type==='checkbox'?e.target.checked:e.target.value;});
content.addEventListener('change',e=>{if(e.target.getAttribute('aria-label')==='Appointment timezone'){displayZone=e.target.value;render(false);}});
content.addEventListener('submit',e=>{e.preventDefault();if(!e.target.reportValidity())return;step=3;render();});
document.querySelectorAll('[data-start-booking]').forEach(a=>a.addEventListener('click',()=>{document.querySelector('.journey').hidden=false;setTimeout(()=>document.querySelector('.journey').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'}),0);}));
document.querySelector('#offer-select').addEventListener('change',e=>location.assign(e.target.value));
render(false);
